[package]
name = "demand"
version = "0.1.1"
edition = "2021"
description = "A CLI prompt library"
license = "MIT"
repository = "https://github.com/jdx/demand"
readme = "README.md"
keywords = ["cli", "prompt", "console"]
files = ["src", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
console = "0.15"
termcolor = "1"
